from apps.hr_department.validators.jwt_validators import JwtTokenValidator, AdminJwtTokenValidator
from apps.hr_department.validators.fields_validators import INNValidator, SNILSValidator, PassportValidator
