services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_DB: "hrdb"
      POSTGRES_USER: "master"
      POSTGRES_PASSWORD: "9D9*1$!kVZRo"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U master -d hrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - backend
networks:
  backend:
    name: elastic