# Generated by Django 4.1.3 on 2023-01-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('save_as_draft', models.BooleanField()),
                ('full_name', models.TextField(default=None)),
                ('date_of_birthday', models.DateField(default=None)),
                ('gender_gender', models.TextField(choices=[('MALE', 'Муж'), ('FEMALE', 'Жен')], default=None)),
                ('inn_number', models.IntegerField(default=None)),
                ('inn_photo', models.ImageField(upload_to='./pictures')),
                ('snils_number', models.IntegerField(default=None)),
                ('snils_photo', models.ImageField(upload_to='./pictures')),
                ('passport_series_and_number', models.IntegerField(default=None)),
                ('passport_issued_by', models.TextField(default=None)),
                ('passport_date_of_issue', models.DateField(default=None)),
                ('passport_division_code', models.IntegerField(default=None)),
                ('passport_registered_address', models.TextField(default=None)),
                ('passport_photos', models.ImageField(default=None, upload_to='')),
                ('place_of_birthday', models.TextField(default=None)),
                ('citizenship', models.TextField(default=None)),
                ('address_of_residence', models.TextField(default=None)),
                ('is_civil_servant', models.BooleanField(default=None)),
                ('date_of_vaccination', models.DateField(default=None)),
                ('education', models.TextField(default=None)),
                ('grade', models.IntegerField(default=None)),
                ('salary', models.IntegerField(default=None)),
                ('premium', models.IntegerField(default=None)),
                ('job_descriptions', models.TextField(default=None)),
                ('mvo', models.IntegerField(default=None)),
                ('quarterly_option', models.IntegerField(default=None)),
                ('annual_option', models.IntegerField(default=None)),
                ('three_year_option', models.IntegerField(default=None)),
                ('cash_year_content', models.IntegerField(default=None)),
                ('cash_month_content', models.IntegerField(default=None)),
                ('cashyear_without_option_content', models.IntegerField(default=None)),
                ('cash_month_without_option_content', models.IntegerField(default=None)),
                ('department', models.TextField(default=None)),
                ('module', models.TextField(default=None)),
                ('position', models.TextField(default=None)),
                ('housing', models.TextField(default=None)),
            ],
        ),
    ]
