# Generated by Django 4.1.5 on 2023-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='is_editable',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='is_editable',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
