# Generated by Django 4.1.6 on 2023-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='status',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='status',
            field=models.TextField(default=None, null=True),
        ),
    ]
