# Generated by Django 3.2.15 on 2023-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0002_draftemployeeinformation_serveremployeeinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='is_checked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='is_checked',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
