# Generated by Django 4.1.6 on 2023-02-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0002_draftemployeeinformation_is_editable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='childrens_birth_certificates_date_of_birthday',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='childrens_birth_certificates_full_name',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='childrens_birth_certificates_relation_degree',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_date_of_issue',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_date_range_of_education',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_education_type',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_educational_institution_name',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_language_proficiency',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_photo',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_qualification',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_series_and_number',
        ),
        migrations.RemoveField(
            model_name='draftemployeeinformation',
            name='education_document_speciality',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='childrens_birth_certificates_date_of_birthday',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='childrens_birth_certificates_full_name',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='childrens_birth_certificates_relation_degree',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_date_of_issue',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_date_range_of_education',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_education_type',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_educational_institution_name',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_language_proficiency',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_photo',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_qualification',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_series_and_number',
        ),
        migrations.RemoveField(
            model_name='serveremployeeinformation',
            name='education_document_speciality',
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='childrens',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='education',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='childrens',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='education',
            field=models.JSONField(default=None, null=True),
        ),
    ]
