# Generated by Django 4.1.6 on 2023-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0003_rename_first_vaccination_date_draftemployeeinformation_vaccination_first_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='im_foreigner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='im_foreigner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
