# Generated by Django 4.1.6 on 2023-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0004_children_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='first_vaccination_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='second_vaccination_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_di_award',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_mbo_award_quarter',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_monthly_mbo_award',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_quarterly_option',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_quasi_option',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_salary',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='draftemployeeinformation',
            name='wage_yearly_option',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='date_range_of_education',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='language_proficiency',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='first_vaccination_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='second_vaccination_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_di_award',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_mbo_award_quarter',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_monthly_mbo_award',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_quarterly_option',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_quasi_option',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_salary',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serveremployeeinformation',
            name='wage_yearly_option',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='childrens',
            field=models.ManyToManyField(default=[], null=True, to='hr_department.children'),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='education',
            field=models.ManyToManyField(default=[], null=True, to='hr_department.education'),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='childrens',
            field=models.ManyToManyField(default=[], null=True, to='hr_department.children'),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='education',
            field=models.ManyToManyField(default=[], null=True, to='hr_department.education'),
        ),
    ]
