# Generated by Django 4.1.6 on 2023-02-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0005_draftemployeeinformation_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftemployeeinformation',
            old_name='childrens',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='serveremployeeinformation',
            old_name='childrens',
            new_name='children',
        ),
    ]
