# Generated by Django 4.1.6 on 2023-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0006_rename_childrens_draftemployeeinformation_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='inn_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='migration_card_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='military_document_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='notice_of_registration_in_russia_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='passport_reversal_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='patent_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='residence_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='snils_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='temporary_residence_permit_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draftemployeeinformation',
            name='work_permit_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='inn_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='migration_card_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='military_document_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='notice_of_registration_in_russia_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='passport_reversal_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='patent_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='residence_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='snils_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='temporary_residence_permit_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serveremployeeinformation',
            name='work_permit_photo',
            field=models.ImageField(default='pictures/default.jpeg', null=True, upload_to=''),
        ),
    ]
