fields_frontend = [
    'full_name__full_name',
    'date_of_birthday__date',
    'gender__gender',
    'inn__number',
    'inn__photo',
    'snils__number',
    'snils__photo',
    'passport__series_and_number',
    'passport__issued_by',
    'passport__date_of_issue',
    'passport__division_code',
    'passport__registered_address',
    'passport__photo_reversal',
    'passport__photo_registration',
    'place_of_birthday__place',
    'citizenship__citizenship',
    'address_of_residence__address',
    'is_civil_servant__is_civil_servant',
    'date_of_vaccination__date',
    'education__education',
    'grade__grade',
    'salary__salary',
    'premium__premium',
    'job_descriptions__descriptions',
    'mvo__mvo',
    'options__quarterly_option',
    'options__annual_option',
    'options__three_year_option',
    'сash_content__cash_year__content',
    'сash_content__cash_month__content',
    'сash_content__cashyear_without_option__content',
    'сash_content__cash_month_without_option__content',
    'department__department',
    'module__module',
    'position__position',
    'housing__housing',
]

fields_backend = [
    'full_name',
    'date_of_birthday',
    'gender_gender',
    'inn_number',
    'inn_photo',
    'snils_number',
    'snils_photo',
    'passport_series_and_number',
    'passport_issued_by',
    'passport_date_of_issue',
    'passport_division_code',
    'passport_registered_address',
    'passport_photo1',
    'passport_photo2',
    'place_of_birthday',
    'citizenship',
    'address_of_residence',
    'is_civil_servant',
    'date_of_vaccination',
    'education',
    'grade',
    'salary',
    'premium',
    'job_descriptions',
    'mvo',
    'quarterly_option',
    'annual_option',
    'three_year_option',
    'cash_year_content',
    'cash_month_content',
    'cashyear_without_option_content',
    'cash_month_without_option_content',
    'department',
    'module',
    'position',
    'housing'
]

fields_frontend_to_backend = {
  "full_name__full_name": "full_name",
  "date_of_birthday__date": "date_of_birthday",
  "gender__gender": "gender_gender",
  "inn__number": "inn_number",
  "inn__photo": "inn_photo",
  "snils__number": "snils_number",
  "snils__photo": "snils_photo",
  "passport__series_and_number": "passport_series_and_number",
  "passport__issued_by": "passport_issued_by",
  "passport__date_of_issue": "passport_date_of_issue",
  "passport__division_code": "passport_division_code",
  "passport__registered_address": "passport_registered_address",
  "passport__photo_reversal": "passport_photo1",
  "passport__photo_registration": "passport_photo2",
  "place_of_birthday__place": "place_of_birthday",
  "citizenship__citizenship": "citizenship",
  "address_of_residence__address": "address_of_residence",
  "is_civil_servant__is_civil_servant": "is_civil_servant",
  "date_of_vaccination__date": "date_of_vaccination",
  "education__education": "education",
  "grade__grade": "grade",
  "salary__salary": "salary",
  "premium__premium": "premium",
  "job_descriptions__descriptions": "job_descriptions",
  "mvo__mvo": "mvo",
  "options__quarterly_option": "quarterly_option",
  "options__annual_option": "annual_option",
  "options__three_year_option": "three_year_option",
  "сash_content__cash_year__content": "cash_year_content",
  "сash_content__cash_month__content": "cash_month_content",
  "сash_content__cashyear_without_option__content": "cashyear_without_option_content",
  "сash_content__cash_month_without_option__content": "cash_month_without_option_content",
  "department__department": "department",
  "module__module": "module",
  "position__position": "position",
  "housing__housing": "housing"
}

date_fields = [
    'date_of_birthday',
    'date_of_issue',
    'date_of_vaccination',
    'passport_date_of_issue',
]
