fields_frontend = [
    'im_foreigner__im_foreigner',
    'full_name__full_name',
    'date_of_birthday__date',
    'citizenship__citizenship',
    'place_of_birthday__place',
    'email__email',
    'phone_number__phone_number',
    'addresses__address_outside_russia',
    'addresses__address_for_information',
    'married_status__relation_degree',
    'married_status__full_name',
    'married_status__date_of_birthday',
    'status_of_the_insured_person__status',
    'gender__gender',
    'passport__series_and_number',
    'passport__issued_by',
    'passport__date_of_issue',
    'passport__division_code',
    'passport__valid_until',
    'passport__registration_date',
    'passport__registered_address',
    'passport__reversal_photo',
    'passport__registration_photo',
    'education_document__education_type',
    'education_document__educational_institution_name',
    'education_document__speciality',
    'education_document__qualification',
    'education_document__series_and_number',
    'education_document__date_of_issue',
    'education_document__date_range_of_education',
    'education_document__language_proficiency',
    'education_document__photo',
    'military_document__relation_to_military_duty',
    'military_document__rank',
    'military_document__composition',
    'military_document__stock_category',
    'military_document__vus',
    'military_document__fitness',
    'military_document__commissariat',
    'military_document__relation_to_military_registration',
    'military_document__photo',
    'childrens_birth_certificates__full_name',
    'childrens_birth_certificates__date_of_birthday',
    'childrens_birth_certificates__relation_degree',
    'snils__number',
    'snils__photo',
    'inn__number',
    'inn__photo',
    'work_permit__series_and_number',
    'work_permit__date_of_issue',
    'work_permit__valid_until',
    'work_permit__issued_by',
    'work_permit__photo',
    'residence__series_and_number',
    'residence__date_of_issue',
    'residence__valid_until',
    'residence__issued_by',
    'residence__photo',
    'patent__series_and_number',
    'patent__date_of_issue',
    'patent__valid_until',
    'patent__issued_by',
    'patent__photo',
    'temporary_residence_permit__series_and_number',
    'temporary_residence_permit__date_of_issue',
    'temporary_residence_permit__valid_until',
    'temporary_residence_permit__issued_by',
    'temporary_residence_permit__photo',
    'migration_card__photo',
    'notice_of_registration_in_russia__photo',
]

fields_backend = [
    'full_name',
    'date_of_birthday',
    'gender_gender',
    'inn_number',
    'inn_photo',
    'snils_number',
    'snils_photo',
    'passport_series_and_number',
    'passport_issued_by',
    'passport_date_of_issue',
    'passport_division_code',
    'passport_registered_address',
    'passport_photo1',
    'passport_photo2',
    'place_of_birthday',
    'citizenship',
    'address_of_residence',
    'is_civil_servant',
    'date_of_vaccination',
    'education',
    'grade',
    'salary',
    'premium',
    'job_descriptions',
    'mvo',
    'quarterly_option',
    'annual_option',
    'three_year_option',
    'cash_year_content',
    'cash_month_content',
    'cash_year_without_option_content',
    'cash_month_without_option_content',
    'department',
    'module',
    'position',
    'housing'
]

fields_frontend_to_backend = {
  "full_name__full_name": "full_name",
  "date_of_birthday__date": "date_of_birthday",
  "gender__gender": "gender_gender",
  "inn__number": "inn_number",
  "inn__photo": "inn_photo",
  "snils__number": "snils_number",
  "snils__photo": "snils_photo",
  "passport__series_and_number": "passport_series_and_number",
  "passport__issued_by": "passport_issued_by",
  "passport__date_of_issue": "passport_date_of_issue",
  "passport__division_code": "passport_division_code",
  "passport__registered_address": "passport_registered_address",
  "passport__photo_reversal": "passport_photo1",
  "passport__photo_registration": "passport_photo2",
  "place_of_birthday__place": "place_of_birthday",
  "citizenship__citizenship": "citizenship",
  "address_of_residence__address": "address_of_residence",
  "is_civil_servant__is_civil_servant": "is_civil_servant",
  "date_of_vaccination__date": "date_of_vaccination",
  "education__education": "education",
  "grade__grade": "grade",
  "salary__salary": "salary",
  "premium__premium": "premium",
  "job_descriptions__descriptions": "job_descriptions",
  "mvo__mvo": "mvo",
  "options__quarterly_option": "quarterly_option",
  "options__annual_option": "annual_option",
  "options__three_year_option": "three_year_option",
  "сash_content__cash_year__content": "cash_year_content",
  "сash_content__cash_month__content": "cash_month_content",
  "сash_content__cashyear_without_option__content": "cash_year_without_option_content",
  "сash_content__cash_month_without_option__content": "cash_month_without_option_content",
  "department__department": "department",
  "module__module": "module",
  "position__position": "position",
  "housing__housing": "housing"
}

# using for and zip
fields_backend_to_frontend = {
    key: value for key, value in zip(fields_backend, fields_frontend)
}

date_fields = [
    # TODO
]
